synonymdict = {
    "black pepper": "pepper",
    "onions": "onion",
    "vanilla extract": "vanilla",
    "sea salt": "salt",
    "heavy cream": "cream",
    "chicken breasts": "chicken",
    "chocolate chips": "chocolate",
    "lime juice": "lime",
    "egg yolks": "eggs",
    "egg whites": "eggs",
    "wine vinegar": "vinegar",
    "dijon mustard": "mustard",
    "white wine": "wine",
    "yellow onion": "onion",
    "orange juice": "orange",
    "white sugar": "sugar",
    "bay leaf": "bay leaves",
    "cider vinegar": "vinegar",
    "scallions": "green onions",
    "balsamic vinegar": "vinegar",
    "cashew nuts": "cashews",
    "lemon zest": "lemon",
    "caster sugar": "sugar",
    "greek yogurt": "yogurt",
    "confectioners sugar": "sugar",
    "tomato paste": "tomatoes",
    "onion powder": "onion",
    "basil leaves": "basil",
    "leaf parsley": "parsley",
    "cherry tomatoes": "tomatoes",
    "wheat flour": "flour",
    "rice vinegar": "vinegar",
    "cloves": "clove",
    "chicken breast": "chicken",
    "dark chocolate": "chocolate",
    "red wine": "wine",
    "pumpkin purée": "pumpkin",
    "white pepper": "pepper",
    "sweet chocolate": "chocolate",
    "celery ribs": "celery",
    "active yeast": "yeast",
    "corn syrup": "sugar",
    "almond extract": "almonds",
    "white onion": "onion",
    "chicken thighs": "chicken",
    "white vinegar": "vinegar",
    "whipped cream": "cream",
    "spring onions": "green onions",
    "half & half": "cream",
    "chicken stock": "chicken broth",
    "vegetable stock": "vegetable broth",
    "beef stock": "beef broth",
    "cocoa": "chocolate",
    "cocoa powder": "chocolate",
    "lean beef": "beef",
    "baby spinach": "spinach",
    "parsley leaves": "parsley",
    "butternut squash": "squash",
    "bread flour": "flour",
    "evaporated milk": "milk",
    "sweet onion": "onion",
    "coconut sugar": "sugar",
    "almond flour": "flour",
    "black olives": "olives",
    "plum tomatoes": "tomatoes",
    "semisweet chocolate": "chocolate",
    "brown rice": "rice",
    "pinenuts": "pine nuts",
    "coconut flakes": "coconut",
    "unbleached flour": "flour",
    "mint leaves": "mint",
    "vanilla beans": "vanilla",
    "orange zest": "orange",
    "cake flour": "flour",
    "black peppercorns": "pepper",
    "coconut flour": "flour",
    "russet potatoes": "potatoes",
    "wite rice": "rice",
    "crushed tomatoes": "tomatoes",
    "spaghetti": "noodles",
    "romaine lettuce": "lettuce",
    "sun tomatoes": "tomatoes",
    "rice flour": "flour",
    "bittersweet chocolate": "chocolate",
    "corn kernels": "corn",
    "mushroom soup": "mushrooms",
    "bread crumbs": "breadcrumbs",
    "spinach leaves": "spinach",
    "red potato": "potatoes",
    "fennel seeds": "fennel",
    "sherry": "wine",
    "cooking oil": "oil",
    "seasoning salt": "salt",
    "cracker crumbs": "graham crackers",
    "corn flour": "flour",
    "mini marshmallows": "marshmallows",
    "grape tomatoes": "tomatoes",
    "cool whip": "mayonnaise",
    "pineapple juice": "pineapple",
    "roma tomatoes": "tomatoes",
    "artichoke hearts": "artichokes",
    "ghee": "butter",
    "crème fraîche": "cream",
    "skim milk": "milk",
    "lime wedges": "lime",
    "chili flakes": "chili",
    "coriander seeds": "coriander",
    "whipped topping": "cream",
    "gold potatoes": "potatoes",
    "meat": "beef",
    "white flour": "flour",
    "button mushrooms": "mushrooms",
    "pork chops": "pork",
    "tomato purée": "tomato sauce",
    "apple juice": "apples",
    "sausages": "sausage",
    "instant yeast": "yeast",
    "finely onion": "onion",
    "italian sausage": "sausage",
    "baguette": "bread",
    "nutritional yeast": "yeast",
    "prosciutto": "ham",
    "lemon peel": "lemon",
    "lime zest": "lime",
    "red cabbage": "cabbage",
    "boiled egg": "eggs",
    "softened butter": "butter",
    "sage leaves": "sage",
    "white bread": "bread",
    "vanilla bean": "vanilla",
    "ginger root": "ginger",
    "pork tenderloin": "pork",
    "lemon wedges": "lemon",
    "crushed pineapple": "pineapple",
    "steak": "beef",
    "golden raisins": "raisins",
    "egg noodles": "noodles",
    "french bread": "bread",
    "pastry flour": "flour",
    "caramels": "caramel",
    "salad greens": "lettuce",
    "cane sugar": "sugar",
    "vegetable shortening": "shortening",
    "almond meal": "flour",
    "mozzarella": "mozzarella cheese",
    "fennel bulb": "fennel",
    "simple syrup": "sugar",
    "lettuce leaves": "lettuce",
    "table salt": "salt",
    "green olives": "olives",
    "basmati rice": "rice",
    "kalamata": "olives",
    "elbow macaroni": "noodles",
    "vanilla essence": "vanilla",
    "mirin": "wine",
    "milk chocolate": "chocolate",
    "orange peel": "orange",
    "stevia": "sugar",
    "stevia extract": "sugar",
    "stock": "broth",
    "shiitake": "mushrooms",
    "dark rum": "rum",
    "grain mustard": "mustard",
    "espresso powder": "coffee",
    "cocktail cherries": "cherries",
    "cherry": "cherries",
    "hamburger buns": "bread",
    "garlic paste": "garlic",
    "garlic powder": "garlic",
    "english cucumber": "cucumber",
    "pork loin": "pork",
    "icing": "frosting",
    "caramel sauce": "caramel",
    "sherry vinegar": "vinegar",
    "lasagna noodles": "noodles",
    "chicken wings": "chicken",
    "baking potatoes": "potatoes",
    "baby carrots": "carrots",
    "turkey breast": "turkey",
    "medjool date": "date",
    "sweet paprika": "paprika",
    "yellow mustard": "mustard",
    "peppercorns": "pepper",
    "peppermint extract": "peppermint",
    "medium carrot": "carrots",
    "ricotta": "ricotta cheese",
    "cremini mushrooms": "mushrooms",
    "sweetener": "sugar",
    "penne pasta": "noodles",
    "pasta": "noodles",
    "pomegranate seeds": "pomegranate",
    "duck breasts": "duck",
    "oat flour": "flour",
    "pork shoulder": "pork",
    "bbq sauce": "barbecue sauce",
    "green cabbage": "cabbage",
    "vanilla yogurt": "yogurt",
    "flaked coconut": "coconut",
    "cardamom pods": "cardamom",
    "flank steak": "beef",
    "sweet corn": "corn",
    "caraway seeds": "caraway",
    "portabello mushroom": "mushrooms",
    "arborio rice": "rice",
    "mustard powder": "mustard",
    "chipotles in adobo": "chipotle chile",
    "chilli": "chile peppers",
    "chillies": "chile peppers",
    "steaks": "beef",
    "linguine": "noodles",
    "apple": "apples",
    "medium shrimp": "shrimp",
    "garbanzo beans": "chickpeas",
    "yellow squash": "squash",
    "flax seed": "flaxseed",
    "cheery": "cherries",
    "prawns": "shrimp",
    "grating cheese": "parmesan cheese",
    "instant coffee": "coffee",
    "peeled ginger": "ginger",
    "pitted dates": "dates",
    "snow peas": "peas",
    "parsley flakes": "parsley",
    "gingerroot": "ginger",
    "chili pepper": "chile peppers",
    "chili peppers": "chile peppers",
    "yellow peppers": "bell pepper",
    "chuck": "beef",
    "chocolate syrup": "chocolate",
    "cranberry juice": "cranberries",
    "coriander powder": "coriander",
    "turbinado": "sugar",
    "brewed coffee": "coffee",
    "flax seeds": "flaxseed",
    "golden syrup": "sugar",
    "celery salt": "salt",
    "medium tomatoes": "tomatoes",
    "sugar substitute": "sugar",
    "chorizo": "sausage",
    "pecan": "pecans",
    "rice noodles": "noodles",
    "stewed tomatoes": "tomatoes",
    "buns": "bread",
    "green chili": "green chile",
    "green chilies": "green chile",
    "macaroni": "noodles",
    "crimini mushrooms": "mushrooms",
    "rice wine": "wine",
    "sugar pea": "peas",
    "beaten eggs": "eggs",
    "iceberg lettuce": "lettuce",
    "lemon extract": "lemon",
    "green peas": "peas",
    "lemon pepper": "pepper",
    "mandarin oranges": "orange",
    "raspberry jam": "raspberries",
    "tarragon leaves": "tarragon",
    "superfine sugar": "sugar",
    "sirloin steak": "beef",
    "tomato juice": "tomatoes",
    "tomato": "tomatoes",
    "medium zucchini": "zucchini",
    "himalayan salt": "salt",
    "mixed berries": "berries",
    "spelt flour": "flour",
    "quick oats": "oats",
    "sourdough bread": "bread",
    "chuck roast": "beef",
    "teas": "tea",
    "tapioca flour": "flour",
    "wild rice": "rice",
    "fine salt": "salt",
    "tea bags": "tea",
    "parmesan": "parmesan cheese",
    "vanilla pods": "vanilla",
    "medium eggs": "eggs",
    "marshmallow creme": "marshammlows",
    "baby arugula": "arugula",
    "tomato": "tomatoes",
    "red lentils": "lentils",
    "chicken bouillon": "chicken broth",
    "brownie mix": "chocolate",
    "oregano leaves": "oregano",
    "baking mix": "flour",
    "crushed garlic": "garlic",
    "panko": "breadcrumbs",
    "white mushrooms": "mushrooms",
    "tomato soup": "tomato sauce",
    "red onions": "purple onion",
    "mixed vegetables": "vegetables",
    "espresso": "chocolate",
    "pork sausages": "sausage",
    "tapioca starch": "flour",
    "baking chocolate": "chocolate",
    "cold milk": "milk",
    "veal": "beef",
    "canned tomatoes": "tomatoes",
    "rice cereal": "cereal",
    "m&m's candy": "chocolate",
    "chipotle chili": "chipotle chile",
    "wheat bread": "bread",
    "crabmeat": "crab meat",
    "crumbs": "breadcrumbs",
    "zest": "lemon",
    "apricot": "apricots",
    "rosemary leaves": "rosemary",
    "spaghetti squash": "squash",
    "sultana": "raisins",
    "stew meat": "beef",
    "candy canes": "candy",
    "herbes": "herbes de provence",
    "peeled tomatoes": "tomatoes",
    "coconut extract": "coconut",
    "queso fresco": "cheese",
    "saffron threads": "saffron",
    "marsala wine": "wine",
    "butterscotch chips": "caramel",
    "napa cabbage": "cabbage",
    "jasmine rice": "rice",
    "crystallized ginger": "ginger",
    "fettucine": "noodles",
    "fettucine pasta": "noodles",
    "veggies": "vegetables",
    "italian bread": "bread",
    "pepitas": "pumpkin seeds",
    "vegan butter": "butter",
    "dill weed": "dill",
    "free milk": "milk",
    "crusty bread": "bread",
    "rotisserie chicken": "chicken",
    "milk powder": "milk",
    "medium potatoes": "potatoes",
    "roast": "beef",
    "tart apples": "apples",
    "pomegranate juice": "pomegranate",
    "egg": "eggs",
    "orange liqueur": "triple sec",
    "penne": "noodles",
    "capsicum": "bell pepper",
    "shells": "pasta",
    "spanish onion": "onion",
    "asparagus spears": "asparagus",
    "celery root": "celery",
    "bourbon whiskey": "whiskey",
    "grapefruit juice": "grapefruit",
    "lemon rind": "lemon",
    "muscovado sugar": "sugar",
    "sirloin": "beef",
    "strawberry jam": "strawberries",
    "dill pickles": "pickles",
    "apricot jam": "apricots",
    "kernel corn": "corn",
    "sausage links": "sausage",
    "finely pecans": "pecans",
    "sea scallops": "scallops",
    "cacao nibs": "cacao",
    "green apples": "apples",
    "onion flakes": "onion",
    "chicken drumsticks": "chicken",
    "red grapes": "grapes",
    "chicken fingers": "chicken",
    "red potatoes": "potatoes",
    "pickle relish": "relish",
    "buckwheat flour": "flour",
    "green tea": "tea",
    "coffee granules": "coffee",
    "potato": "potatoes",
    "chocolate bars": "chocolate",
    "carrot": "carrots",
    "coconut aminos": "coconut",
    "brown mustard": "mustard",
    "apricot preserves": "apricot",
    "champagne vinegar": "vinegar",
    "chicken legs": "chicken",
    "acorn squash": "squash",
    "anchovies": "anchovy",
    "kale leaves": "kale",
    "roasting chickens": "chicken",
    "silken tofu": "tofu",
    "mace": "nutmeg",
    "chorizo sausage": "sausage",
    "summer squash": "squash",
    "bean": "bean paste",
    "shaoxing wine": "wine",
    "english muffins": "bread",
    "toast": "bread",
    "pearl onions": "onion",
    "basil pesto": "pesto",
    "palm sugar": "sugar",
    "swerve sweetener": "sugar",
    "hamburger": "beef",
    "peach": "peaches",
    "pearl barley": "barley",
    "beef brisket": "beef",
    "finely parsley": "parsley",
    "demerara sugar": "sugar",
    "angel hair": "noodles",
    "navel oranges": "orange",
    "salsa verde": "salsa",
    "thai basil": "basil",
    "coconut butter": "coconut oil",
    "pasta shells": "noodles",
    "tomato ketchup": "ketchup",
    "rotini": "noodles",
    "bacon bits": "bacon",
    "fig": "figs",
    "nectarines": "peaches",
    "balsamico bianco": "vinegar",
    "erythritol": "sugar",
    "soup": "broth",
    "ginger paste": "ginger",
    "blood orange": "orange",
    "shiitake mushrooms": "mushrooms",
    "chicken pieces": "chicken",
    "semolina": "flour",
    "graham cracker": "graham crackers",
    "rigatoni": "noodles",
    "wheat tortillas": "tortillas",
    "corn tortillas": "tortillas",
    "flour tortillas": "tortillas",
    "chickpea flour": "flour",
    "walnut": "walnuts",
    "sandwich bread": "bread",
    "curry": "curry powder",
    "pork roast": "pork",
    "dogs": "hot dogs",
    "fish stock": "fish broth",
    "white rum": "rum",
    "vanilla powder": "vanilla",
    "butter oil": "butter",
    "orzo pasta": "orzo",
    "andouille sausage": "sausage",
    "rolls": "dinner rolls",
    "corn flakes": "cereal",
    "walnut pieces": "walnuts",
    "vanilla wafers": "vanilla",
    "tomato passata": "tomato sauce",
    "porcini mushrooms": "mushrooms",
    "saltines": "crackers",
    "orange extract": "orange",
    "candy melts": "candy",
    "clarified butter": "butter",
    "pork belly": "pork",
    "leaf lettuce": "lettuce",
    "butter lettuce": "lettuce",
    "lean turkey": "turkey",
    "short ribs": "beef",
    "bisquick": "flour",
    "green lentil": "lentils",
    "ramen noodles": "noodles",
    "toffee bits": "caramel",
    "turkey sausage": "sausage",
    "ritz crackers": "crackers",
    "rye bread": "bread",
    "rye flour": "flour",
    "split peas": "peas",
    "fleur de sel": "salt",
    "rib": "beef",
    "peppermint": "candy",
    "liquid stevia": "sugar",
    "stuffing mix": "stuffing",
    "chunky salsa": "salsa",
    "sherry wine": "wine",
    "pesto sauce": "pesto",
    "buttery spread": "butter",
    "hass avocado": "avocado",
    "breakfast sausages": "sausage",
    "cumin seed": "cumin",
    "thyme leaves": "thyme"
    "ripe olives": "olives",
    "deli ham": "ham",
    "soba noodles": "noodles",
    "salad oil": "oil",
    "cheese tortellini": "noodles",
    "yoghurt": "yogurt",
    "crisco": "oil",
    "candy bars": "chocolate",
    "fingerling potatoes": "potatoes",
    "cinnamon sticks": "cinnamon",
    "clear honey": "sugar",
    "currant": "currants",
    "baby potatoes": "potatoes",
    "meyer lemons": "lemon",
    "lemons": "lemon",
    "streaky bacon": "bacon",
    "crab": "crab meat",
    "red apples": "apples",
    "skirt steak": "beef",
    "chocolate shavings": "chocolate",
    "pecan halves": "pecans",
    "mexican oregano": "oregano",
    "french baguette": "bread",
    "poblano chilies": "poblano peppers",
    "wild mushrooms": "mushrooms",
    "chicken sausage": "sausage",
    "tuna steaks": "tuna",
    "savoy cabbage": "cabbage",
    "neutral oil": "oil",
    "szechwan peppercorns": "pepper",
    "yellow cornmeal": "cornmeal",
    "white cornmeal": "cornmeal",
    "jumbo shrimp": "shrimp",
    "corned beef": "beef",
    "stout": "beer",
    "pudding mix": "pudding",
    "wholemeal flour": "flour",
    "fire tomatoes": "tomatoes",
    "mixed herbs": "herbs",
    "yolk": "eggs",
    "orange rind": "orange",
    "fusilli": "noodles",
    "brown lentils": "lentils",
    "mint sprigs": "mint",
    "lemon slices": "lemon",
    "rubbed sage": "sage",
    "lacinato kale": "kale",
    "feta": "feta cheese",
    "garlic cloves": "garlic",
    "rolled oats": "oats",
    "cilantro leaves": "cilantro",
    "green pepper": "bell pepper",
    "bell peppers": "bell pepper",
    "panko breadcrumbs": "breadcrumbs",
    "pistachio nuts": "pistacios",



    #crescent rolls, biscuits, "dinner rolles"
    #"pudding": "milk; sugar; corn starch; salt"
    "steak seasoning": "pepper; paprika; salt; garlic; onion",
    "pico de gallo": "tomato; cilantro; onion; salt",
    "alfredo sauce": "butter; cream; garlic; parmesan cheese; parsley",
    "slaw mix": "cabbage; carrots",
    "lemon curd": "lemon; sugar; butter; eggs; salt",
    "cinnamon sugar": "cinnamon; sugar",
    "lemonade": "lemon; sugar",
    "vanilla sugar": "vanilla; sugar",
    "cajun seasoning": "paprika; salt; pepper; garlic; onion; thyme; cayenne",
    "creole seasoning": "paprika; salt; pepper; garlic; onion; thyme; cayenne",
    "pizza doughs": "flour; yeast; salt; oil",
    "pizza crust": "flour; yeast; salt; oil",
    "pasta sauce": "tomato sauce; basil; oregano",
    "pizza sauce": "tomato sauce; basil; oregano",
    "marinara sauce": "tomato sauce; basil; oregano",
    "pie crust": "flour; shortening; water; salt",
    "pie shell": "flour; shortening; water; salt",
    "piecrusts": "flour; shortening; water; salt",
    "puff pastry": "butter; salt; flour",
    "pastry": "butter; salt; flour",
    "phyllo dough": "butter; salt; flour",
    "phyllo pastry": "butter; salt; flour",
    "garlic salt": "garlic; salt",
    "onion salt": "onion; salt",
    "italian seasoning": "basil; marjoram; oregano; rosemary; thyme; garlic",
    "cake mix": "flour; sugar; baking soda; oil; sugar; salt",
    "cake": "flour; sugar; baking soda; oil; sugar; salt",
    #"curry powder": "cumin; cardamom; coriander; turmeric; mustard; cayenne"
    #"bread": "flour; yeast; oil; salt",
    "taco seasoning": "chili; garlic; onion; pepper; oregano; cumin; salt",
    "dulce de leche": "milk; sugar; baking soda; vanilla"


}

deletethese = set([
    "water",
    "warm water",
    "cold water",
    "boiling water",
    "ice cubes",
    "gluten",
    "ice water",
    "cooking spray",
    "xantham gum",
    "nonstick",
    "liquid",
    "extract",
    "crushed ice",
    "seasoning mix",
    "essence",
    "asafoetida",
    "carbonated water",
    "pectin",
    "rose water",
    "sauce",
    "ice",
    "cooking",
    "",
    "leaves"
])